#!/usr/bin/env bash
# Shared repo-hygiene bloat guard.
# Reads newline-separated candidate paths on stdin; exits non-zero on any violation.
#   SIZE_SRC=index     -> sizes/attrs from the git index        (pre-commit)
#   SIZE_SRC=rev REV=X -> sizes/attrs from commit X's blobs      (pre-push, CI)
#   SIZE_SRC=worktree  -> sizes/attrs from the working tree      (manual / fallback)
# ASCII only (git-bash on Windows must not choke on the byte stream).
set -euo pipefail

MAX_BYTES=$((5 * 1024 * 1024))   # 5 MiB cap for non-allowlisted files

FORBIDDEN_PREFIXES=(
  "docs/review/"
  "docs/devlog/screenshots/"
)
FORBIDDEN_FILES=(
  "Assets/Scenes/Anemora_FastVS_HouseSlice.unity"
  "Assets/Scenes/Anemora_FastVS_HouseSlice.unity.meta"
)
# APV / lighting bake output: regenerated by a bake, not source.
FORBIDDEN_REGEX='Assets/Settings/.*\.Cell(Data|SupportData|OptionalData|ProbeOcclusionData|BricksData|SharedData)\.bytes(\.meta)?$'
# Legitimate large SOURCE allowed above the cap (kept in normal git; LFS is NOT used).
ALLOWLIST_REGEX='^(Assets/UI/Localization/Fonts/Anemora_(JP|EN)_Atlas\.asset|Assets/Editor/AnemoraFastVsHouseSliceSetup\.cs|Assets/Art/External/QuaterniusP0PropKit/FantasyProps/Chest_Wood\.fbx)$'

SRC="${SIZE_SRC:-index}"
fail=0
report() { printf 'BLOCKED  %-9s %s\n    -> %s\n' "$2" "$1" "$3" >&2; fail=1; }

blob_size() {
  case "$SRC" in
    index)    git cat-file -s ":$1"        2>/dev/null || echo 0 ;;
    rev)      git cat-file -s "${REV}:$1"  2>/dev/null || echo 0 ;;
    worktree) if [ -f "$1" ]; then wc -c <"$1"; else echo 0; fi ;;
    *)        echo 0 ;;
  esac
}

# True if the .gitattributes being introduced enables Git LFS (forbidden: it
# breaks the anemora-viewer build, which reads bytes via git archive + blob:none).
attr_has_lfs() {
  case "$SRC" in
    index)    git cat-file blob ":.gitattributes"       2>/dev/null | grep -Eq '^[^#]*filter=lfs' ;;
    rev)      git cat-file blob "${REV}:.gitattributes" 2>/dev/null | grep -Eq '^[^#]*filter=lfs' ;;
    worktree) [ -f .gitattributes ] && grep -Eq '^[^#]*filter=lfs' .gitattributes ;;
    *)        return 1 ;;
  esac
}

while IFS= read -r f; do
  [ -z "$f" ] && continue

  for p in "${FORBIDDEN_PREFIXES[@]}"; do
    case "$f" in "$p"*) report "$f" PATH "ephemeral review image -> Cloudflare R2 (must not be committed)";; esac
  done

  for x in "${FORBIDDEN_FILES[@]}"; do
    [ "$f" = "$x" ] && report "$f" GENERATED "procedurally generated by AnemoraFastVsHouseSliceSetup.cs -> gitignore + regenerate"
  done

  printf '%s' "$f" | grep -Eq "$FORBIDDEN_REGEX" && report "$f" BAKE "APV/lighting bake output -> gitignore (regenerated by a bake)"

  if [ "$f" = ".gitattributes" ] && attr_has_lfs; then
    report ".gitattributes" LFS "filter=lfs breaks the viewer (git archive + blob:none) -> LFS is forbidden in this repo"
  fi

  sz=$(blob_size "$f")
  if [ "$sz" -gt "$MAX_BYTES" ]; then
    if printf '%s' "$f" | grep -Eq "$ALLOWLIST_REGEX"; then
      : # allowlisted large source (font atlas) -> pass
    else
      report "$f" SIZE "$((sz / 1048576))MB > 5MB -> move to R2/gitignore, or add to ALLOWLIST_REGEX if it is a true source"
    fi
  fi
done

exit $fail
